name: Workflow lors d'un push
on : push
jobs:
  premier_workflow:
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
    with:
      distribution: 'zulu' # See 'Supported distributions' for available options
      java-version: '21'
    - run: java Exo2EtudiantApplication.java
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml