name: Workflow lors d'un fork

on:
  fork:

jobs:
  premier-job:
    runs-on: ubuntu-latest
    steps:
      - name: Message après un fork
        env:
          MA_VARIABLE: ${{ vars.MA_VARIABLE }}
          MON_SECRET: ${{ secrets.MON_SECRET }}
          ACTOR: ${{ github.actor }}
        run: |
          echo "Le secret est $MON_SECRET"
          echo "Ma variable est $MA_VARIABLE"
          echo "Le fork a été fait par $ACTOR"
